version: '2.4'
services:
  bootnode:
    image: hyperledger/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      #      "--min-gas-price=0",
      "--node-private-key-file=/opt/besu/keys/key"
    ]
    volumes:
      - ./data:/opt/besu/data
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/genesis.json:/config/genesis.json
      - ./config/besu/key:/opt/besu/keys
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 9545:9545/tcp
      - 30303:30303/tcp
